import { app, BrowserWindow, ipcMain, dialog } from 'electron';
import { readFileSync } from 'fs';
import { saveFile } from './utils';
import * as Buffer from 'buffer';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1300,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    title: 'TA3',
    icon: 'assets/images/ADBOU-skeletonsLilla',
    useContentSize: true,
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

//  ---- IPC FUNCTIONS ----
// Below we have defined functions for IPC between the Main and the Renderer process

/**
 * Handles the IPC request for compiling and saving the contents in the latexString
 * to a PDF file.
 * Precondition: The function will fail if the user is not running with admin privileges and if they don't have LaTeX installed to their path
 */
ipcMain.on('savePDF', async (_, latexString) => {
  let options = {
    title: 'Save file',
    defaultPath: app.getPath('documents'),
    filters: [{ name: 'Settings', extensions: ['pdf'] }],
  };
  const filename = await dialog.showSaveDialog(options);

  if (!filename.canceled) {
    const fs = require('fs');
    const latex = require('node-latex');

    const output = fs.createWriteStream(filename.filePath);
    const pdf = await latex(latexString, { passes: 2 }); // 2 passes for references (LastPage)
    pdf.pipe(output);
    pdf.on('error', () =>
      dialog.showErrorBox(
        'Error',
        'LaTeX has not been found on your machine. Please make sure that you have installed the newest version of LaTeX, since LaTeX is required for this functionality and is running the program with administrative privileges. If this is not the case then please contact the administrator.'
      )
    );
  }
});

/**
 * Handles the IPC request for saving the string contents to a file.
 * The user is prompted to enter a filename or cancel the operation.
 */
ipcMain.on('saveTXT', async (_, content: string) => {
  let options = {
    title: 'Save file',
    defaultPath: app.getPath('documents'),
    filters: [{ name: 'Settings', extensions: ['txt'] }],
  };

  const filename = await dialog.showSaveDialog(options);
  if (!(filename.canceled || filename.filePath === ''))
    saveFile(filename, content);
});

/**
 * Handles the IPC request for saving the contents to a file using the csv format.
 * The user is prompted to enter a filename or cancel the operation.
 */
ipcMain.on('saveCSV', async (_, content: string) => {
  let options = {
    title: 'Save file',
    defaultPath: app.getPath('documents'),
    filters: [{ name: 'Settings', extensions: ['csv'] }],
  };

  const filename = await dialog.showSaveDialog(options);
  if (!filename.canceled) saveFile(filename, content);
});

/**
 * Handles the IPC request that reads a csv file and returns the string rows of the csv file.
 * Precondition: Each entry is separated by a newline character.
 */
ipcMain.handle('readCSV', async (_): Promise<string[]> => {
  let options = {
    defaultPath: app.getPath('documents'),
    filters: [{ name: 'Settings', extensions: ['csv'] }],
  };
  const filename = await dialog.showOpenDialog(options);
  let stringRows: string[] = [];

  if (!filename.canceled) {
    const raw = readFileSync(filename.filePaths[0]);
    stringRows = raw.toString().split(/\n/); // split the content into rows
    stringRows = stringRows.map((line) => line.replace(/<nl>/g, '\n')); // convert the newlines back
  }

  return stringRows;
});

/**
 * Handles the IPC request for saving the contents to a file using the fa3 format.
 * The user is prompted to enter a filename or cancel the operation.
 */
ipcMain.on('saveTA3', async (_, content: string) => {
  let options = {
    title: 'Save file',
    defaultPath: app.getPath('documents'),
    filters: [{ name: 'Settings', extensions: ['ta3'] }],
  };

  const filename = await dialog.showSaveDialog(options);
  if (!filename.canceled)
    saveFile(filename, Buffer.Buffer.from(content).toString('base64'));
});

/**
 * Handles the IPC request that reads a ta3 file and returns the string rows of the ta3 file.
 * Precondition: Each entry is separated by a newline character.
 */
ipcMain.handle('readTA3', async (_): Promise<string> => {
  let options = {
    defaultPath: app.getPath('documents'),
    filters: [{ name: 'Settings', extensions: ['ta3'] }],
  };
  const filename = await dialog.showOpenDialog(options);
  let jsonObj: string = '';

  if (!filename.canceled) {
    const raw = readFileSync(filename.filePaths[0]);
    jsonObj = Buffer.Buffer.from(raw.toString(), 'base64').toString();
  }
  return jsonObj;
});
