import * as utils from "../utils";
import { Analysis } from "../datatypes/Analysis";
import * as TransistionAnalysis from "../TransitionAnalysis";

// The prologue of the LaTeX file.
const prologue = `
\\documentclass[12pt]{article}
\\usepackage{fancyhdr}
\\usepackage{lastpage}
\\usepackage{csquotes}
\\usepackage{pgfplots}
\\pgfplotsset{width=10cm,compat=1.9}
\\pagestyle{fancy}
\\renewcommand{\\familydefault}{\\sfdefault}
\\lhead{Transition Analysis}
\\rhead{Date: \\today}
\\cfoot{Page \\thepage\\ of \\pageref{LastPage}}
\\lfoot{}

\\begin{document}

\\begin{titlepage}
   \\begin{center}
       \\vspace*{1cm}

       \\textbf{\\huge Transition Analysis \\\\ Output Report}

       \\vspace{0.5cm}
        Generated by Transition Analysis\\\\
        \\today

   \\end{center}
\\end{titlepage}

\\tableofcontents
\\newpage
`;

// The epilogue for the LaTeX file.
const epilogue = "\\end{document}";

/**
 * Converts an analysis to a LaTeX formatted string.
 * @param analysis The analysis to convert.
 * @returns A string representation in LaTeX format of the analysis.
 */
function generateLatexContent(analysis: Analysis) {
  const scores = utils.flattenAnalysisScores(analysis);
  const estimates = TransistionAnalysis.calculateEstimates(
    scores,
    analysis.subjectSex,
    analysis.subjectRegion,
  );

  // Chi square value should not be affected by prior age distributions
  const chiSquareProbability = TransistionAnalysis.calculateIntervals(
    scores.length,
    estimates,
    TransistionAnalysis.confidenceIntervals.confidence80,
  ).bestEstimateProbability;

  if (analysis.subjectPriorAgeDistributionName) {
    TransistionAnalysis.adjustWithPriorAgeDistribution(
      estimates,
      analysis.subjectPriorAgeDistributionName,
    );
  }

  const confidenceInterval95 = TransistionAnalysis.calculateIntervals(
    scores.length,
    estimates,
    TransistionAnalysis.confidenceIntervals.confidence95,
  );
  const confidenceInterval90 = TransistionAnalysis.calculateIntervals(
    scores.length,
    estimates,
    TransistionAnalysis.confidenceIntervals.confidence90,
  );
  const confidenceInterval80 = TransistionAnalysis.calculateIntervals(
    scores.length,
    estimates,
    TransistionAnalysis.confidenceIntervals.confidence80,
  );

  let content = "";
  content += `\\section{Case: ${analysis.name}}`;

  content += `\\begin{itemize}`;
  content += `\\item Case name: ${analysis.name}`;
  content += `\\item Specimen sex: ${analysis.subjectSex}`;
  content += `\\item Specimen region: ${analysis.subjectRegion}`;
  content += `\\end{itemize}`;

  if (analysis.notes) {
    content += `\\subsection{Case notes} ${analysis.notes}`;
  }

  content += `\\subsection{Age estimates}`;
  content += `\\begin{itemize}`;
  content += `\\item Osteological estimate: ${confidenceInterval95.pointEstimate.toFixed(1)} years.`;
  content += `\\item Unbiased estimate: ${confidenceInterval95.unbiasedPointEstimate.toFixed(1)} years.`;
  content += `\\item Prior distribution used: ${
    analysis.subjectPriorAgeDistributionName
      ? analysis.subjectPriorAgeDistributionName
      : "None"
  }`;
  content += `\\item Unbiased Confidence 95%: [${confidenceInterval95.unbiasedPointEstimateLowerBound} : ${confidenceInterval95.unbiasedPointEstimateUpperBound}]`;
  content += `\\item Unbiased Confidence 90%: [${confidenceInterval90.unbiasedPointEstimateLowerBound} : ${confidenceInterval90.unbiasedPointEstimateUpperBound}]`;
  content += `\\item Unbiased Confidence 80%: [${confidenceInterval80.unbiasedPointEstimateLowerBound} : ${confidenceInterval80.unbiasedPointEstimateUpperBound}]`;
  const curveScores = utils.flattenAnalysisScores(analysis);
  const degreesOfFreedom = utils.getDegreesOfFreedom(curveScores);
  content += `\\item $\\chi^2$ with ${degreesOfFreedom} degrees of freedom: $${(
    -2 * chiSquareProbability
  ).toFixed(5)}$`;
  content += `\\end{itemize}`;

  if (scores.length > 0) {
    content += `
      \\begin{tikzpicture}
        \\begin{axis}[
          title={Support curve for age estimate},
          xlabel={Age},
          ylabel={Logarithmic probability},
          grid style=dashed,
          ymax=0,
          legend pos=south east,
          legend style={font=\\tiny},
        ]
        \\addplot[
          color=blue,
          mark=,
        ]
        coordinates { `;

    let coordinatesStr = "";
    for (let i = 0; i < estimates.length; i += 1) {
      // Trim the graph so it only shows the values that are > (best estimate - 15)
      const estimateValue = estimates[i][1];
      const thresholdIndex = Math.round((confidenceInterval80.unbiasedPointEstimate - 15) * 10);
      const thresholdValue = estimates[thresholdIndex] ? estimates[thresholdIndex][1] : -Infinity;
      
      // Skip invalid values and apply threshold filter
      if (isFinite(estimateValue) && estimateValue > thresholdValue - 15) {
        coordinatesStr += `(${estimates[i][0]},${estimateValue.toFixed(5)})`;
      }
    }
    content += `${coordinatesStr}}; \\addlegendentry{support curve}`;

    // confidence lines
    const lowestProbability = estimates.reduce((min, current) =>
      min[1] < current[1] ? min : current,
    )[1];
    
    // Guard against -Infinity or very small values
    const confidenceLineBorder = lowestProbability === -Infinity || lowestProbability < -1000 
      ? -1000 
      : lowestProbability + lowestProbability;

    content += `
    \\draw[red, thick] (axis cs:${confidenceInterval80.unbiasedPointEstimateLowerBound}, ${confidenceLineBorder}) -- (axis cs:${confidenceInterval80.unbiasedPointEstimateLowerBound}, 0);
    \\draw[red, thick] (axis cs:${confidenceInterval80.unbiasedPointEstimateUpperBound}, ${confidenceLineBorder}) -- (axis cs:${confidenceInterval80.unbiasedPointEstimateUpperBound}, 0);
    \\addlegendimage{red, thick}
    \\addlegendentry{80% confidence}

    \\draw[green, thick, dashed] (axis cs:${confidenceInterval90.unbiasedPointEstimateLowerBound}, ${confidenceLineBorder}) -- (axis cs:${confidenceInterval90.unbiasedPointEstimateLowerBound}, 0);
    \\draw[green, thick, dashed] (axis cs:${confidenceInterval90.unbiasedPointEstimateUpperBound}, ${confidenceLineBorder}) -- (axis cs:${confidenceInterval90.unbiasedPointEstimateUpperBound}, 0);
    \\addlegendimage{green, thick, dashed}
    \\addlegendentry{90% confidence}

    \\draw[blue, thick, dotted] (axis cs:${confidenceInterval95.unbiasedPointEstimateLowerBound}, ${confidenceLineBorder}) -- (axis cs:${confidenceInterval95.unbiasedPointEstimateLowerBound}, 0);
    \\draw[blue, thick, dotted] (axis cs:${confidenceInterval95.unbiasedPointEstimateUpperBound}, ${confidenceLineBorder}) -- (axis cs:${confidenceInterval95.unbiasedPointEstimateUpperBound}, 0);
    \\addlegendimage{blue,thick,dotted}
    \\addlegendentry{95% confidence}
    `;
    content += `
        \\end{axis}
      \\end{tikzpicture}
    `;
  }

  content += `\\subsection{Observations}`;
  if (analysis.scores.length > 0) {
    content += `\\begin{itemize}`;
    for (const score of analysis.scores) {
      content += `\\item ${score[0].name} : ${score[1].name}`;
    }
    content += `\\end{itemize}`;
  } else {
    content += `\\textit{(No observations were made...)}`;
  }

  content += `\\newpage`;

  // Handle special characters
  content = content.replace(/>=/g, "$\\ge$");
  content = content.replace(/<=/g, "$\\le$");
  content = content.replace(/</g, "$<$");
  content = content.replace(/>/g, "$>$");
  content = content.replace(/%/g, "\\%");

  return content;
}

/**
 * Generates a PDF and asks the user to save it to their filesystem.
 * @param analyses The analyses made in the application.
 */
export function generatePDF(analyses: Analysis[]) {
  let content = "";

  for (const analysis of analyses) {
    content += generateLatexContent(analysis);
  }
  window.api.savePDF(prologue + content + epilogue);
}
